server:
  port: 88
#spring:
#  jpa:
#    database: h2
#    properties: # JAP 설정
#      hibernate:
#        # 하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
#        show_sql: true
#        # 콘솔에 출력되는 JPA 실행 쿼리를 가독성 있게 표현한다.
#        format_sql: true
#        # 디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
#        use_sql_comments: true